name: FairUHC Plugin
author: Qzop
version: 1.0
main: me.fairuhc.UHC.Main
description: This will be the fairuhc UHC plugin!
             
commands:
  scenarios:
    description: See scenarios.
  scen:
    description: See scenarios
  sa:
    description: Players with permission can edit the scenarios.
  uhc:
    description: Will send a list of commands to use with /uhc.
  config:
    description: Will send a list of configs that are on or off.
  ca:
    description: Players with this permission can turn configs on or off.
  team:
    description: List of all team commands.
  health:
    description: Sends player the health of a player.
  kt:
    description: Sends player list of top killers in the game. 
  numteams:
    description: Sends player the number of teams.
  sc:
    description: Sends teammates your coordinates.
  sethost:
    description: Sets player in spectator mode.
  removehost:
    description: Removes player from spectator mode.
  regeneratemap:
    description: Regenerates the map.
  practice:
    description: sends player to practice map.
  gt:
    description: dev command.
  loadchunks:
    description: command to load chunks in the uhc world.
  sdbreload:
    description: Reloads the cofig.
  stats:
    description: Shows a players in game stats. 
  helpop:
    description: Ask staff a question.
  report:
    description: Report a player.
  mod:
    description: Sets player in spectator mode.
  border:
    description: shrinks the border.
  respawn:
    description: Respawns a player into the game.
  heal:
    description: Heals a player.
  give:
    description: Gives players items.
 